var menus = {
    corp: {
        name: '海底捞火锅'
    },
    category: [{ id: 1, name: '招牌菜' }, { id: 2, name: '凉菜' }, { id: 3, name: '热菜' }, { id: 4, name: '主食' }, { id: 5, name: '酒水' }, { id: 6, name: '饮料'}],
    dishes: [{
        id: 1,
        name: '鱼香肉丝',
        des: '精品川菜',
        price: 25,
        vipPrice: 23,
        img: 'yxrs.jpg'
    }, {
        id: 2,
        name: '宫保鸡丁',
        des: '精品川菜',
        price: 25,
        vipPrice: 23,
        img: 'gbjd.jpg'
    }, {
        id: 3,
        name: '百合虾仁',
        des: '口感香甜',
        price: 50,
        vipPrice: 48,
        img: 'bhxr.jpg'
    }, {
        id: 4,
        name: '四喜丸子',
        des: '精品丸子',
        price: 36,
        vipPrice: 32,
        img: 'sxwz.jpg'
    }, {
        id: 5,
        name: '卤水拼盘',
        des: '精品凉菜',
        price: 35,
        vipPrice: 32,
        img: 'lspp.jpg'
    }, {
        id: 6,
        name: '千层饼',
        des: '主食',
        price: 18,
        vipPrice: 16,
        img: 'qcb.jpg'
    }, {
        id: 7,
        name: '五粮液国宴酒',
        des: '正品五粮液',
        price: 525,
        vipPrice: 515,
        img: 'wlygy.jpg'
    }, {
        id: 8,
        name: '扇贝',
        des: '新鲜海鲜扇贝',
        price: 89,
        vipPrice: 85,
        img: 'sb.jpg'
    }, {
        id: 9,
        name: 'XO酱小爪鸡杂',
        des: 'XO酱小爪鸡杂',
        price: 25,
        vipPrice: 22,
        img: 'xojxzjz.jpg'
    }, {
        id: 10,
        name: '醋泡双生',
        des: '醋泡双生',
        price: 18,
        vipPrice: 16,
        img: 'cpss.jpg'
    }, {
        id: 11,
        name: '风味泡菜',
        des: '风味泡菜',
        price: 18,
        vipPrice: 16,
        img: 'fwpc.jpg'
    }, {
        id: 12,
        name: '高碑店豆腐丝',
        des: '高碑店豆腐丝',
        price: 18,
        vipPrice: 16,
        img: 'gbddfs.jpg'
    }, {
        id: 13,
        name: '花豆腐干',
        des: '花豆腐干',
        price: 20,
        vipPrice: 18,
        img: 'hdfg.jpg'
    }, {
        id: 14,
        name: '金丝银缕',
        des: '金丝银缕',
        price: 25,
        vipPrice: 22,
        img: 'jsyl.jpg'
    }, {
        id: 15,
        name: '精品凉菜',
        des: '精品凉菜',
        price: 20,
        vipPrice: 18,
        img: 'jplc.jpg'
    }, {
        id: 16,
        name: '苦瓜丝',
        des: '苦瓜丝',
        price: 18,
        vipPrice: 16,
        img: 'kgs.jpg'
    }, {
        id: 17,
        name: '南瓜藤',
        des: '南瓜藤',
        price: 26,
        vipPrice: 24,
        img: 'ngt.jpg'
    }, {
        id: 18,
        name: '田园蔬菜',
        des: '田园蔬菜',
        price: 20,
        vipPrice: 18,
        img: 'tysc.jpg'
    }, {
        id: 19,
        name: '小黄瓜',
        des: '小黄瓜',
        price: 26,
        vipPrice: 24,
        img: 'xhg.jpg'
    }, {
        id: 20,
        name: '叉烧雪鱼炒甜豆',
        des: '叉烧雪鱼炒甜豆',
        price: 30,
        vipPrice: 28,
        img: 'csxyctd.jpg'
    }, {
        id: 21,
        name: '铁板烧茄子',
        des: '铁板烧茄子',
        price: 36,
        vipPrice: 32,
        img: 'tbsqz.jpg'
    }, {
        id: 22,
        name: '芙蓉百合',
        des: '芙蓉百合',
        price: 30,
        vipPrice: 28,
        img: 'frbh.jpg'
    }, {
        id: 23,
        name: '香芒大明虾',
        des: '香芒大明虾',
        price: 28,
        vipPrice: 26,
        img: 'xmdmx.jpg'
    }, {
        id: 24,
        name: '香辣虾',
        des: '香辣虾',
        price: 45,
        vipPrice: 42,
        img: 'xlx.jpg'
    }, {
        id: 25,
        name: '京酱肉丝',
        des: '京酱肉丝',
        price: 36,
        vipPrice: 35,
        img: 'jjrs.jpg'
    }, {
        id: 26,
        name: '粗粮焗排骨',
        des: '粗粮焗排骨',
        price: 52,
        vipPrice: 48,
        img: 'cljpg.jpg'
    }, {
        id: 27,
        name: '虫草花白果煮胜瓜',
        des: '虫草花白果煮胜瓜',
        price: 30,
        vipPrice: 28,
        img: 'cchbgzsg.jpg'
    }, {
        id: 28,
        name: '豉油皇咸肉',
        des: '豉油皇咸肉',
        price: 36,
        vipPrice: 32,
        img: 'qyhxr.jpg'
    }, {
        id: 29,
        name: '深海龙虾',
        des: '深海龙虾',
        price: 60,
        vipPrice: 58,
        img: 'shlx.jpg'
    }, {
        id: 30,
        name: '番茄炒蛋',
        des: '番茄炒蛋',
        price: 18,
        vipPrice: 16,
        img: 'fqcd.jpg'
    }, {
        id: 31,
        name: '干烧明虾',
        des: '干烧明虾',
        price: 46,
        vipPrice: 45,
        img: 'gsmx.jpg'
    }, {
        id: 32,
        name: '叉烧肉',
        des: '叉烧肉',
        price: 40,
        vipPrice: 38,
        img: 'csr.jpg'
    }, {
        id: 33,
        name: '白灼菜心',
        des: '白灼菜心',
        price: 25,
        vipPrice: 22,
        img: 'bzcx.jpg'
    }, {
        id: 34,
        name: '蟹黄',
        des: '蟹黄',
        price: 38,
        vipPrice: 35,
        img: 'xh.jpg'
    }, {
        id: 35,
        name: '虫草花炒爬虾',
        des: '虫草花炒爬虾',
        price: 68,
        vipPrice: 60,
        img: 'cchcpx.jpg'
    }, {
        id: 36,
        name: '芝麻球',
        des: '芝麻球',
        price: 20,
        vipPrice: 18,
        img: 'zmq.jpg'
    }, {
        id: 37,
        name: '葱包烩',
        des: '葱包烩',
        price: 20,
        vipPrice: 18,
        img: 'cbh.jpg'
    }, {
        id: 38,
        name: '烤枣馍片',
        des: '烤枣馍片',
        price: 20,
        vipPrice: 18,
        img: 'kzmp.jpg'
    }, {
        id: 39,
        name: '手抓饼',
        des: '手抓饼',
        price: 20,
        vipPrice: 18,
        img: 'szb.jpg'
    }, {
        id: 40,
        name: '芒果汁',
        des: '芒果汁',
        price: 10,
        vipPrice: 9,
        img: 'mgz.jpg'
    }, {
        id: 41,
        name: '猕猴桃汁',
        des: '猕猴桃汁',
        price: 10,
        vipPrice: 9,
        img: 'mhtz.jpg'
    }, {
        id: 42,
        name: '酸梅汁',
        des: '酸梅汁',
        price: 10,
        vipPrice: 9,
        img: 'smz.jpg'
    }, {
        id: 43,
        name: '珍珠奶茶',
        des: '珍珠奶茶',
        price: 10,
        vipPrice: 9,
        img: 'zznc.jpg'
    }, {
        id: 44,
        name: '白酒S2',
        des: '白酒S2',
        price: 69,
        vipPrice: 65,
        img: 'bjs2.jpg'
    }, {
        id: 45,
        name: '',
        des: '',
        price: 0,
        vipPrice: 0,
        img: '.jpg'
    }],
    pages: [
    { layout: 1, dishes: [23, 5, 25], cateId: 1 },
    { layout: 1, dishes: [5, 9, 10], cateId: 2 },
    { layout: 1, dishes: [11, 12, 13], cateId: 2 },
    { layout: 1, dishes: [14, 15, 16], cateId: 2 },
     { layout: 1, dishes: [17, 18, 19], cateId: 2 },
     { layout: 1, dishes: [1, 2, 3], cateId: 3 },
     { layout: 1, dishes: [4, 8, 20], cateId: 3 },
     { layout: 1, dishes: [21, 22, 23], cateId: 3 },
     { layout: 1, dishes: [24, 25, 26], cateId: 3 },
     { layout: 1, dishes: [27, 28, 29], cateId: 3 },
     { layout: 1, dishes: [30, 31, 32], cateId: 3 },
     { layout: 1, dishes: [33, 34, 35], cateId: 3 },
     { layout: 1, dishes: [36, 37, 38], cateId: 4 },
     { layout: 1, dishes: [39, 7, 44], cateId: 5 },
     { layout: 1, dishes: [41, 42, 43], cateId: 6 },
     { layout: 1, dishes: [40], cateId: 6}]
};
